CREATE TABLE IF NOT EXISTS users (
id BIGSERIAL PRIMARY KEY,
name VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE,
password_hash TEXT NOT NULL,
role VARCHAR(100) NOT NULL DEFAULT 'ROLE_USER',
created_at TIMESTAMP DEFAULT now()
);



